mm := "mindmap-01.otl"
wiki := "Template.wiki"
scale := "60"

build target:
    gvmm-exe.py gvmm -s {{scale}} -f "{{target}}" > /dev/null
    vim -c ':Vimwiki2HTML' -c ':wq' '{{wiki}}' > /dev/null
    galacomm.py -r my_whiteboard > /dev/null || galaview.sh `basename "{{target}}" .otl`.[jp]* &

mindmap: (build mm)
