import copy

from graphviz_mindmaps import constants


_DEFAULTS = {
    "fontcolor": copy.deepcopy(constants.fontcolor),
    "linecolors": copy.deepcopy(constants.linecolors),
    "vrbtcolors": copy.deepcopy(constants.vrbtcolors),
    "nodetype": copy.deepcopy(constants.nodetype),
    "edgetype": copy.deepcopy(constants.edgetype),
    "edgecolors": copy.deepcopy(constants.edgecolors),
    "arrcolors": copy.deepcopy(constants.arrcolors),
}


def ThemeNames():
    return ["default", *THEME_PALETTES]


def _restore_defaults():
    for name, values in _DEFAULTS.items():
        target = getattr(constants, name)
        target.clear()
        target.update(copy.deepcopy(values))
    return constants.DEFAULT_BGCOLOR


def _node(fill, border="#4c566a", shape="box", style="rounded,radial", fontcolor=None, margin=None):
    attrs = [
        "shape=%s" % shape,
        "style=\"%s\"" % style,
        "fontsize=\"%s\"" % constants.fontsize["l"],
        "fillcolor=\"%s\"" % fill,
        "color=\"%s\"" % border,
    ]
    if fontcolor:
        attrs.append("fontcolor=\"%s\"" % fontcolor)
    if margin:
        attrs.append("margin=\"%s\"" % margin)
    return " ".join(attrs)


def _component(fill, border="#4c566a", fontname=None):
    attrs = [
        "shape=component",
        "style=\"radial\"",
        "margin=\"0.15,0.15\"",
        "fillcolor=\"%s\"" % fill,
        "color=\"%s\"" % border,
    ]
    if fontname:
        attrs.insert(1, "fontname=\"%s\"" % fontname)
    return " ".join(attrs)


def _apply_palette(palette):
    fg = palette["fg"]
    bg = palette["bg"]
    panel = palette["panel"]
    border = palette["border"]
    muted = palette["muted"]
    accent = palette["accent"]
    red = palette["red"]
    green = palette["green"]
    blue = palette["blue"]
    yellow = palette["yellow"]
    cyan = palette["cyan"]
    purple = palette["purple"]
    orange = palette["orange"]

    constants.fontcolor.update({
        "def": fg,
        "r": red,
        "g": green,
        "b": blue,
        "y": yellow,
        "c": cyan,
        "p": purple,
        "k": bg,
        "t": fg,
    })

    constants.linecolors.update({
        "r": red,
        "g": green,
        "b": blue,
        "y": yellow,
        "c": cyan,
        "p": purple,
        "k": bg,
    })

    constants.vrbtcolors.update({
        "cdef": panel,
        "cgreen": palette["green_bg"],
        "cred": palette["red_bg"],
        "cblue": palette["blue_bg"],
        "ccyan": palette["cyan_bg"],
        "cyello": palette["yellow_bg"],
        "corang": palette["orange_bg"],
        "cpink": palette["purple_bg"],
        "cwhite": palette["white_bg"],
        "def": palette["verbatim_bg"],
    })

    constants.nodetype.update({
        "root": "fontsize=\"%s\" margin=\"0.5\" shape=cds style=radial color=\"%s\" fillcolor=\"%s\" gradientangle=\"90\" fontcolor=\"%s\"" % (constants.fontsize["xxl"], accent, panel, fg),
        "def": "shape=underline fontcolor=\"%s\" color=\"%s\"" % (fg, border),
        "underl": "shape=underline fontcolor=\"%s\" color=\"%s\"" % (fg, border),
        "node": _node(panel, border=border, fontcolor=fg),
        "list": _node(palette["cyan_bg"], border=border, shape="rect", style="radial", fontcolor=fg),
        "data": _node(panel, border=border, shape="cylinder", style="radial", fontcolor=fg, margin="0.1,0.3"),
        "answer": _node(palette["green_bg"], border=green, shape="cds", style="radial", fontcolor=fg, margin="0.2"),
        "quest": _node(palette["yellow_bg"], border=yellow, shape="oval", style="radial", fontcolor=fg, margin="0,0"),
        "title": "shape=doubleoctagon fontname=\"%s\" margin=\"0,0\" fontsize=\"%s\" style=\"radial\" fillcolor=\"%s\" color=\"%s\" fontcolor=\"%s\"" % (constants.font["comicb"], constants.fontsize["l"], accent, blue, fg),
        "impor": "shape=signature fontsize=\"%s\" margin=\"0.25\" style=\"radial\" fillcolor=\"%s\" color=\"%s\" fontcolor=\"%s\"" % (constants.fontsize["l"], palette["red_bg"], red, fg),
        "impog": "shape=signature fontsize=\"%s\" margin=\"0.25\" style=\"radial\" fillcolor=\"%s\" color=\"%s\" fontcolor=\"%s\"" % (constants.fontsize["l"], palette["green_bg"], green, fg),
        "impob": "shape=signature fontsize=\"%s\" margin=\"0.25\" style=\"radial\" fillcolor=\"%s\" color=\"%s\" fontcolor=\"%s\"" % (constants.fontsize["l"], palette["blue_bg"], blue, fg),
        "impoy": "shape=signature fontsize=\"%s\" margin=\"0.25\" style=\"radial\" fillcolor=\"%s\" color=\"%s\" fontcolor=\"%s\"" % (constants.fontsize["l"], palette["yellow_bg"], yellow, fg),
        "img": _node(panel, border=border, shape="none", style="radial", fontcolor=fg),
        "imgil": _node(panel, border=border, style="radial", fontcolor=fg),
        "dood": "shape=underline fontcolor=\"%s\" color=\"%s\"" % (fg, border),
        "date": "shape=component gradientangle=\"270\" style=\"filled\" margin=\"0.15,0.15,0.15\" fillcolor=\"%s;0.93:%s\" color=\"%s\" fontcolor=\"%s\"" % (panel, red, border, fg),
        "link": "shape=component gradientangle=\"270\" style=\"filled\" margin=\"0.15,0.15,0.15\" fillcolor=\"%s;0.93:%s\" color=\"%s\" fontcolor=\"%s\"" % (panel, blue, border, fg),
        "example": "shape=note fontname=\"%s\" gradientangle=\"270\" style=\"filled\" margin=\"0.15,0.15\" fillcolor=\"%s;0.15:%s\" color=\"%s\" fontcolor=\"%s\"" % (constants.font["mono"], palette["green_bg"], panel, border, fg),
        "draw": _component(constants.vrbtcolors["cwhite"], border=border, fontname=constants.font["mono"]),
        "verbatim": _component(constants.vrbtcolors["def"], border=border, fontname=constants.font["mono"]),
        "commen": "shape=note fontname=\"%s\" fontsize=\"%s\" margin=\"0.2\" style=\"radial\" fillcolor=\"%s\" color=\"%s\" fontcolor=\"%s\"" % (constants.font["comic"], constants.fontsize["l"], palette["yellow_bg"], border, fg),
        "term": "shape=note fontname=\"%s\" gradientangle=\"270\" style=\"filled\" margin=\"0.15,0.15\" fillcolor=\"%s\" color=\"%s\" fontcolor=\"%s\"" % (constants.font["mono"], panel, border, fg),
        "check": "shape=rarrow margin=\"0.20\" style=\"filled\" fillcolor=\"%s\" fontcolor=\"%s\" color=\"%s\"" % (panel, fg, blue),
        "todo": "shape=box margin=\"0.20\" fontsize=\"18\" style=\"filled, diagonals\" fillcolor=\"%s\" fontcolor=\"%s\" color=\"%s\"" % (palette["yellow_bg"], fg, yellow),
        "decisi": _node(palette["orange_bg"], border=orange, shape="diamond", fontcolor=fg),
        "saying": _node(palette["cyan_bg"], border=cyan, shape="egg", style="radial", fontcolor=fg, margin="0.0,0.15"),
        "cgreen": _node(palette["green_bg"], border=green, fontcolor=fg),
        "ccyan": _node(palette["cyan_bg"], border=cyan, fontcolor=fg),
        "cblue": _node(palette["blue_bg"], border=blue, fontcolor=fg),
        "cpink": _node(palette["purple_bg"], border=purple, fontcolor=fg),
        "cred": _node(palette["red_bg"], border=red, fontcolor=fg),
        "cyello": _node(palette["yellow_bg"], border=yellow, fontcolor=fg),
        "corang": _node(palette["orange_bg"], border=orange, fontcolor=fg),
        "cgrey": _node(muted, border=border, fontcolor=fg),
        "cblack": _node(bg, border=border, fontcolor=fg),
    })

    constants.edgetype.update({
        "impor": "style=\"bold\" color=\"%s\"" % red,
        "impog": "style=\"bold\" color=\"%s\"" % green,
        "impob": "style=\"bold\" color=\"%s\"" % blue,
        "impoy": "style=\"bold\" color=\"%s\"" % yellow,
        "cred": "color=\"%s\"" % red,
        "cgreen": "color=\"%s\"" % green,
        "cblue": "color=\"%s\"" % blue,
        "ccyan": "color=\"%s\"" % cyan,
        "cyello": "color=\"%s\"" % yellow,
        "cpink": "color=\"%s\"" % purple,
        "corang": "color=\"%s\"" % orange,
    })

    constants.edgecolors.update({
        "r": "color=\"%s\"" % red,
        "g": "color=\"%s\"" % green,
        "b": "color=\"%s\"" % blue,
        "c": "color=\"%s\"" % cyan,
        "y": "color=\"%s\"" % yellow,
        "p": "color=\"%s\"" % purple,
    })
    constants.arrcolors.update({
        "d": fg,
        "r": red,
        "g": green,
        "b": blue,
        "y": yellow,
        "c": cyan,
        "p": purple,
    })

    return palette["bg"]


THEME_PALETTES = {
    "nord": {
        "bg": "#2e3440",
        "fg": "#eceff4",
        "panel": "#3b4252",
        "border": "#4c566a",
        "muted": "#4c566a",
        "accent": "#5e81ac",
        "red": "#bf616a",
        "green": "#a3be8c",
        "blue": "#81a1c1",
        "yellow": "#ebcb8b",
        "cyan": "#88c0d0",
        "purple": "#b48ead",
        "orange": "#d08770",
        "red_bg": "#5b3d43",
        "green_bg": "#3f5142",
        "blue_bg": "#344154",
        "yellow_bg": "#4a4634",
        "cyan_bg": "#34494d",
        "purple_bg": "#47394d",
        "orange_bg": "#4d3d34",
        "white_bg": "#eceff4",
        "verbatim_bg": "#3b4252",
    },
    "papercolor": {
        "bg": "#eeeeee",
        "fg": "#444444",
        "panel": "#ffffff",
        "border": "#bcbcbc",
        "muted": "#d0d0d0",
        "accent": "#0087af",
        "red": "#af0000",
        "green": "#008700",
        "blue": "#005faf",
        "yellow": "#d7af00",
        "cyan": "#0087af",
        "purple": "#8787af",
        "orange": "#d75f00",
        "red_bg": "#ffd7d7",
        "green_bg": "#d7ffd7",
        "blue_bg": "#d7eaff",
        "yellow_bg": "#fff5cc",
        "cyan_bg": "#d7ffff",
        "purple_bg": "#eadfff",
        "orange_bg": "#ffe6d7",
        "white_bg": "#ffffff",
        "verbatim_bg": "#f7f7f7",
    },
    "papercolor-dark": {
        "bg": "#1c1c1c",
        "fg": "#d0d0d0",
        "panel": "#303030",
        "border": "#5f5f5f",
        "muted": "#444444",
        "accent": "#5fafaf",
        "red": "#af5f5f",
        "green": "#5faf5f",
        "blue": "#5fafd7",
        "yellow": "#d7af5f",
        "cyan": "#5fafaf",
        "purple": "#af87d7",
        "orange": "#d7875f",
        "red_bg": "#3a2828",
        "green_bg": "#283a28",
        "blue_bg": "#283440",
        "yellow_bg": "#3c3628",
        "cyan_bg": "#283a3a",
        "purple_bg": "#342c40",
        "orange_bg": "#3c3028",
        "white_bg": "#eeeeee",
        "verbatim_bg": "#262626",
    },
    "monokai": {
        "bg": "#272822",
        "fg": "#f8f8f2",
        "panel": "#3e3d32",
        "border": "#75715e",
        "muted": "#49483e",
        "accent": "#66d9ef",
        "red": "#f92672",
        "green": "#a6e22e",
        "blue": "#66d9ef",
        "yellow": "#e6db74",
        "cyan": "#a1efe4",
        "purple": "#ae81ff",
        "orange": "#fd971f",
        "red_bg": "#4a2634",
        "green_bg": "#344622",
        "blue_bg": "#263f46",
        "yellow_bg": "#49452a",
        "cyan_bg": "#284844",
        "purple_bg": "#3b3153",
        "orange_bg": "#4c351f",
        "white_bg": "#f8f8f2",
        "verbatim_bg": "#2f3029",
    },
    "gruvbox": {
        "bg": "#282828",
        "fg": "#ebdbb2",
        "panel": "#3c3836",
        "border": "#665c54",
        "muted": "#504945",
        "accent": "#83a598",
        "red": "#fb4934",
        "green": "#b8bb26",
        "blue": "#83a598",
        "yellow": "#fabd2f",
        "cyan": "#8ec07c",
        "purple": "#d3869b",
        "orange": "#fe8019",
        "red_bg": "#4c2f2a",
        "green_bg": "#45472a",
        "blue_bg": "#334349",
        "yellow_bg": "#4d4227",
        "cyan_bg": "#374832",
        "purple_bg": "#493642",
        "orange_bg": "#4d3928",
        "white_bg": "#fbf1c7",
        "verbatim_bg": "#32302f",
    },
    "solarized": {
        "bg": "#002b36",
        "fg": "#93a1a1",
        "panel": "#073642",
        "border": "#586e75",
        "muted": "#16424d",
        "accent": "#268bd2",
        "red": "#dc322f",
        "green": "#859900",
        "blue": "#268bd2",
        "yellow": "#b58900",
        "cyan": "#2aa198",
        "purple": "#6c71c4",
        "orange": "#cb4b16",
        "red_bg": "#4b2f35",
        "green_bg": "#34422c",
        "blue_bg": "#123f55",
        "yellow_bg": "#443d22",
        "cyan_bg": "#123f43",
        "purple_bg": "#30364f",
        "orange_bg": "#4a3328",
        "white_bg": "#fdf6e3",
        "verbatim_bg": "#073642",
    },
    # Published base/accent colors; node fills blend 14% accent into the panel.
    "solarized-light": {
        "bg": "#fdf6e3",
        "fg": "#657b83",
        "panel": "#eee8d5",
        "border": "#93a1a1",
        "muted": "#eee8d5",
        "accent": "#268bd2",
        "red": "#dc322f",
        "green": "#859900",
        "blue": "#268bd2",
        "yellow": "#b58900",
        "cyan": "#2aa198",
        "purple": "#6c71c4",
        "orange": "#cb4b16",
        "red_bg": "#ebcfbe",
        "green_bg": "#dfddb7",
        "blue_bg": "#d2dbd5",
        "yellow_bg": "#e6dbb7",
        "cyan_bg": "#d3decc",
        "purple_bg": "#dcd7d3",
        "orange_bg": "#e9d2ba",
        "white_bg": "#fdf6e3",
        "verbatim_bg": "#eee8d5",
    },
    "catppuccin-latte": {
        "bg": "#eff1f5",
        "fg": "#4c4f69",
        "panel": "#eff1f5",
        "border": "#9ca0b0",
        "muted": "#ccd0da",
        "accent": "#1e66f5",
        "red": "#d20f39",
        "green": "#40a02b",
        "blue": "#1e66f5",
        "yellow": "#df8e1d",
        "cyan": "#179299",
        "purple": "#8839ef",
        "orange": "#fe640b",
        "red_bg": "#ebd1db",
        "green_bg": "#d6e6d9",
        "blue_bg": "#d2def5",
        "yellow_bg": "#ede3d7",
        "cyan_bg": "#d1e4e8",
        "purple_bg": "#e1d7f4",
        "orange_bg": "#f1ddd4",
        "white_bg": "#eff1f5",
        "verbatim_bg": "#eff1f5",
    },
    "rose-pine-dawn": {
        "bg": "#faf4ed",
        "fg": "#464261",
        "panel": "#fffaf3",
        "border": "#9893a5",
        "muted": "#dfdad9",
        "accent": "#286983",
        "red": "#b4637a",
        "green": "#6d8f89",
        "blue": "#286983",
        "yellow": "#ea9d34",
        "cyan": "#56949f",
        "purple": "#907aa9",
        "orange": "#d7827e",
        "red_bg": "#f4e5e2",
        "green_bg": "#ebebe4",
        "blue_bg": "#e1e6e3",
        "yellow_bg": "#fcedd8",
        "cyan_bg": "#e7ece7",
        "purple_bg": "#efe8e9",
        "orange_bg": "#f9e9e3",
        "white_bg": "#faf4ed",
        "verbatim_bg": "#fffaf3",
    },
    "github-light": {
        "bg": "#ffffff",
        "fg": "#1f2328",
        "panel": "#f6f8fa",
        "border": "#d1d9e0",
        "muted": "#e8ecf0",
        "accent": "#0969da",
        "red": "#d1242f",
        "green": "#1a7f37",
        "blue": "#0969da",
        "yellow": "#9a6700",
        "cyan": "#0969da",
        "purple": "#8250df",
        "orange": "#bc4c00",
        "red_bg": "#f1dade",
        "green_bg": "#d7e7df",
        "blue_bg": "#d5e4f6",
        "yellow_bg": "#e9e4d7",
        "cyan_bg": "#d5e4f6",
        "purple_bg": "#e6e0f6",
        "orange_bg": "#eee0d7",
        "white_bg": "#ffffff",
        "verbatim_bg": "#f6f8fa",
    },
    "one-light": {
        "bg": "#fafafa",
        "fg": "#383a42",
        "panel": "#fafafa",
        "border": "#a0a1a7",
        "muted": "#e5e5e6",
        "accent": "#526fff",
        "red": "#e45649",
        "green": "#50a14f",
        "blue": "#4078f2",
        "yellow": "#c18401",
        "cyan": "#0184bc",
        "purple": "#a626a4",
        "orange": "#986801",
        "red_bg": "#f7e3e1",
        "green_bg": "#e2eee2",
        "blue_bg": "#e0e8f9",
        "yellow_bg": "#f2e9d7",
        "cyan_bg": "#d7e9f1",
        "purple_bg": "#eedcee",
        "orange_bg": "#ece6d7",
        "white_bg": "#fafafa",
        "verbatim_bg": "#fafafa",
    },
    "gruvbox-light": {
        "bg": "#fbf1c7",
        "fg": "#3c3836",
        "panel": "#f2e5bc",
        "border": "#a89984",
        "muted": "#d5c4a1",
        "accent": "#076678",
        "red": "#9d0006",
        "green": "#79740e",
        "blue": "#076678",
        "yellow": "#b57614",
        "cyan": "#427b58",
        "purple": "#8f3f71",
        "orange": "#af3a03",
        "red_bg": "#e6c5a3",
        "green_bg": "#e1d5a4",
        "blue_bg": "#d1d3b2",
        "yellow_bg": "#e9d5a4",
        "cyan_bg": "#d9d6ae",
        "purple_bg": "#e4ceb2",
        "orange_bg": "#e9cda2",
        "white_bg": "#fbf1c7",
        "verbatim_bg": "#f2e5bc",
    },
    # Dark adaptations: subdued panels with 14% accent-tinted node fills.
    "dracula": {
        "bg": "#282a36",
        "fg": "#f8f8f2",
        "panel": "#343746",
        "border": "#6272a4",
        "muted": "#44475a",
        "accent": "#bd93f9",
        "red": "#ff5555",
        "green": "#50fa7b",
        "blue": "#8be9fd",
        "yellow": "#f1fa8c",
        "cyan": "#8be9fd",
        "purple": "#bd93f9",
        "orange": "#ffb86c",
        "red_bg": "#503b48",
        "green_bg": "#38524d",
        "blue_bg": "#405060",
        "yellow_bg": "#4e5250",
        "cyan_bg": "#405060",
        "purple_bg": "#47445f",
        "orange_bg": "#50494b",
        "white_bg": "#f8f8f2",
        "verbatim_bg": "#343746",
    },
    "catppuccin-mocha": {
        "bg": "#1e1e2e",
        "fg": "#cdd6f4",
        "panel": "#313244",
        "border": "#6c7086",
        "muted": "#45475a",
        "accent": "#89b4fa",
        "red": "#f38ba8",
        "green": "#a6e3a1",
        "blue": "#89b4fa",
        "yellow": "#f9e2af",
        "cyan": "#94e2d5",
        "purple": "#cba6f7",
        "orange": "#fab387",
        "red_bg": "#4c3e52",
        "green_bg": "#414b51",
        "blue_bg": "#3d445d",
        "yellow_bg": "#4d4b53",
        "cyan_bg": "#3f4b58",
        "purple_bg": "#47425d",
        "orange_bg": "#4d444d",
        "white_bg": "#cdd6f4",
        "verbatim_bg": "#313244",
    },
    "tokyo-night": {
        "bg": "#1a1b26",
        "fg": "#c0caf5",
        "panel": "#24283b",
        "border": "#565f89",
        "muted": "#292e42",
        "accent": "#7aa2f7",
        "red": "#f7768e",
        "green": "#9ece6a",
        "blue": "#7aa2f7",
        "yellow": "#e0af68",
        "cyan": "#7dcfff",
        "purple": "#bb9af7",
        "orange": "#ff9e64",
        "red_bg": "#423347",
        "green_bg": "#353f42",
        "blue_bg": "#303955",
        "yellow_bg": "#3e3b41",
        "cyan_bg": "#303f56",
        "purple_bg": "#393855",
        "orange_bg": "#433941",
        "white_bg": "#c0caf5",
        "verbatim_bg": "#24283b",
    },
    "one-dark": {
        "bg": "#282c34",
        "fg": "#abb2bf",
        "panel": "#303540",
        "border": "#5c6370",
        "muted": "#3e4451",
        "accent": "#528bff",
        "red": "#e06c75",
        "green": "#98c379",
        "blue": "#61afef",
        "yellow": "#e5c07b",
        "cyan": "#56b6c2",
        "purple": "#c678dd",
        "orange": "#d19a66",
        "red_bg": "#493d47",
        "green_bg": "#3f4948",
        "blue_bg": "#374658",
        "yellow_bg": "#494848",
        "cyan_bg": "#354752",
        "purple_bg": "#453e56",
        "orange_bg": "#474345",
        "white_bg": "#abb2bf",
        "verbatim_bg": "#303540",
    },
    "rose-pine": {
        "bg": "#191724",
        "fg": "#e0def4",
        "panel": "#1f1d2e",
        "border": "#6e6a86",
        "muted": "#403d52",
        "accent": "#c4a7e7",
        "red": "#eb6f92",
        "green": "#95b1ac",
        "blue": "#31748f",
        "yellow": "#f6c177",
        "cyan": "#9ccfd8",
        "purple": "#c4a7e7",
        "orange": "#ebbcba",
        "red_bg": "#3c283c",
        "green_bg": "#303240",
        "blue_bg": "#22293c",
        "yellow_bg": "#3d3438",
        "cyan_bg": "#303646",
        "purple_bg": "#363048",
        "orange_bg": "#3c3342",
        "white_bg": "#e0def4",
        "verbatim_bg": "#1f1d2e",
    },
    "kanagawa": {
        "bg": "#1f1f28",
        "fg": "#dcd7ba",
        "panel": "#2a2a37",
        "border": "#54546d",
        "muted": "#363646",
        "accent": "#7e9cd8",
        "red": "#e46876",
        "green": "#98bb6c",
        "blue": "#7e9cd8",
        "yellow": "#e6c384",
        "cyan": "#7aa89f",
        "purple": "#957fb8",
        "orange": "#ffa066",
        "red_bg": "#443340",
        "green_bg": "#393e3e",
        "blue_bg": "#363a4e",
        "yellow_bg": "#443f42",
        "cyan_bg": "#353c46",
        "purple_bg": "#393649",
        "orange_bg": "#483b3e",
        "white_bg": "#dcd7ba",
        "verbatim_bg": "#2a2a37",
    },
    # Dark/light pairs with 14% accent-tinted node fills.
    "everforest-dark": {
        "bg": "#2d353b",
        "fg": "#d3c6aa",
        "panel": "#343f44",
        "border": "#7a8478",
        "muted": "#475258",
        "accent": "#a7c080",
        "red": "#e67e80",
        "green": "#a7c080",
        "blue": "#7fbbb3",
        "yellow": "#dbbc7f",
        "cyan": "#83c092",
        "purple": "#d699b6",
        "orange": "#e69875",
        "red_bg": "#4d484c",
        "green_bg": "#44514c",
        "blue_bg": "#3e5054",
        "yellow_bg": "#4b504c",
        "cyan_bg": "#3f514f",
        "purple_bg": "#4b4c54",
        "orange_bg": "#4d4b4b",
        "white_bg": "#d3c6aa",
        "verbatim_bg": "#343f44",
    },
    "everforest-light": {
        "bg": "#fdf6e3",
        "fg": "#5c6a72",
        "panel": "#f4f0d9",
        "border": "#939f91",
        "muted": "#e6e2cc",
        "accent": "#8da101",
        "red": "#f85552",
        "green": "#8da101",
        "blue": "#3a94c5",
        "yellow": "#dfa000",
        "cyan": "#35a77c",
        "purple": "#df69ba",
        "orange": "#f57d26",
        "red_bg": "#f5dac6",
        "green_bg": "#e6e5bb",
        "blue_bg": "#dae3d6",
        "yellow_bg": "#f1e5bb",
        "cyan_bg": "#d9e6cc",
        "purple_bg": "#f1ddd5",
        "orange_bg": "#f4e0c0",
        "white_bg": "#fdf6e3",
        "verbatim_bg": "#f4f0d9",
    },
    "ayu-dark": {
        "bg": "#10141c",
        "fg": "#bfbdb6",
        "panel": "#141821",
        "border": "#5a6378",
        "muted": "#1b1f29",
        "accent": "#e6b450",
        "red": "#f07178",
        "green": "#aad94c",
        "blue": "#59c2ff",
        "yellow": "#ffb454",
        "cyan": "#95e6cb",
        "purple": "#d2a6ff",
        "orange": "#ff8f40",
        "red_bg": "#33242d",
        "green_bg": "#293327",
        "blue_bg": "#1e3040",
        "yellow_bg": "#352e28",
        "cyan_bg": "#263539",
        "purple_bg": "#2f2c40",
        "orange_bg": "#352925",
        "white_bg": "#bfbdb6",
        "verbatim_bg": "#141821",
    },
    "ayu-light": {
        "bg": "#fcfcfc",
        "fg": "#5c6166",
        "panel": "#f8f9fa",
        "border": "#828e9f",
        "muted": "#ebeef0",
        "accent": "#f29718",
        "red": "#f07171",
        "green": "#86b300",
        "blue": "#22a4e6",
        "yellow": "#eba400",
        "cyan": "#4cbf99",
        "purple": "#a37acc",
        "orange": "#fa8532",
        "red_bg": "#f7e6e7",
        "green_bg": "#e8efd7",
        "blue_bg": "#daedf7",
        "yellow_bg": "#f6edd7",
        "cyan_bg": "#e0f1ec",
        "purple_bg": "#ece7f4",
        "orange_bg": "#f8e9de",
        "white_bg": "#fcfcfc",
        "verbatim_bg": "#f8f9fa",
    },
    "nightfox": {
        "bg": "#192330",
        "fg": "#cdcecf",
        "panel": "#212e3f",
        "border": "#71839b",
        "muted": "#29394f",
        "accent": "#719cd6",
        "red": "#c94f6d",
        "green": "#81b29a",
        "blue": "#719cd6",
        "yellow": "#dbc074",
        "cyan": "#63cdcf",
        "purple": "#9d79d6",
        "orange": "#f4a261",
        "red_bg": "#393345",
        "green_bg": "#2e404c",
        "blue_bg": "#2c3d54",
        "yellow_bg": "#3b4246",
        "cyan_bg": "#2a4453",
        "purple_bg": "#323854",
        "orange_bg": "#3f3e44",
        "white_bg": "#cdcecf",
        "verbatim_bg": "#212e3f",
    },
    "dayfox": {
        "bg": "#f6f2ee",
        "fg": "#3d2b5a",
        "panel": "#f2e9e1",
        "border": "#aab0ad",
        "muted": "#dbd1dd",
        "accent": "#2848a9",
        "red": "#a5222f",
        "green": "#396847",
        "blue": "#2848a9",
        "yellow": "#ac5402",
        "cyan": "#287980",
        "purple": "#6e33ce",
        "orange": "#955f61",
        "red_bg": "#e7cdc8",
        "green_bg": "#d8d7cb",
        "blue_bg": "#d6d2d9",
        "yellow_bg": "#e8d4c2",
        "cyan_bg": "#d6d9d3",
        "purple_bg": "#e0d0de",
        "orange_bg": "#e5d6cf",
        "white_bg": "#f6f2ee",
        "verbatim_bg": "#f2e9e1",
    },

}


def ApplyTheme(name):
    if name == "default":
        return _restore_defaults()
    if name in THEME_PALETTES:
        _restore_defaults()
        return _apply_palette(THEME_PALETTES[name])
    raise ValueError("unknown theme: %s" % name)
